version: "3.8"
services:
  balancer:
    container_name: "balancer"
    image: nginx
    restart: "no"
    volumes:
      - ./balancer/sites-enabled:/etc/nginx/sites-enabled
      - ./balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8081"

  web:
    container_name: "web"
    image: "node:14.15.4"
    restart: "no"
    working_dir: "/mnt/project"
    env_file:
      - .env
    volumes:
      - ../reactblog-web:/mnt/project
      - ../reactblog-core:/mnt/reactblog-core
      - ../reactblog-ui:/mnt/reactblog-ui
      - ../reactblog-node:/mnt/reactblog-node
    command: ["npm", "start"]

  seo_service:
    container_name: "seo_service"
    image: "node:14.15.4"
    restart: "no"
    working_dir: "/mnt/project"
    volumes:
      - ../reactblog-seo-service:/mnt/project
      - ../reactblog-core:/mnt/reactblog-core
      - ../reactblog-ui:/mnt/reactblog-ui
      - ../reactblog-node:/mnt/reactblog-node
      - ../reactblog-web:/mnt/reactblog-web
    command: ["npm", "start"]
    env_file:
      - .env

  redis:
    container_name: "redis"
    image: "redis:alpine"
    restart: "no"
    ports:
      - "6379:6379"
