version: "3.8"
services:
  balancer:
    container_name: "balancer"
    image: nginx
    restart: "no"
    volumes:
      - $PWD/./balancer/sites-enabled:/etc/nginx/sites-enabled
      - $PWD/./balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"

  web:
    container_name: "web"
    image: "node"
    restart: "no"
    working_dir: "/mnt/project"
    volumes:
      - $PWD/../reactblog-web:/mnt/project
      - $PWD/../reactblog-core:/mnt/reactblog/core
      - $PWD/../reactblog-ui:/mnt/reactblog/ui
      - $PWD/../reactblog-node:/mnt/reactblog/node
    command: ["npm", "start"]

  seo_service:
    container_name: "seo_service"
    image: "node"
    restart: "no"
    working_dir: "/mnt/project"
    volumes:
      - $PWD/../reactblog-seo-service:/mnt/project
      - $PWD/../reactblog-core:/mnt/reactblog/core
      - $PWD/../reactblog-ui:/mnt/reactblog/ui
      - $PWD/../reactblog-node:/mnt/reactblog/node
    command: ["npm", "start"]
